### ISSUE TITLE
Handle translations

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/proton-pack#11]
* Merge all `template.pot` files in one and upload it on Crowdin.
* Manage download of new translations.

**Comment by dhoko** [comment]
> Merge all template.pot files in one and upload it on Crowdin.

We should extract the cli from Webclient and use it as a new project instead of using proton-pack for it. (:warning: _about usine à gaz_;))
We don't manage translations with proton-pack as we don't do it today with the Webclient. Imho it's another process linked to the deploy or by hand.
