### ISSUE TITLE
Don't silently ignore/suppress the error occured in "proton.config.js"

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/proton-pack#35]
https://github.com/ProtonMail/proton-pack/blob/2e44d5fd9d2df39787202fc08a90757ea47fe480/cli/config.js#L30-L32

Two options:
- Keeping the same logic but printing the error at least, so it's easier to debug stuff. I would really prefer the second option though (execution flow gets stopped on any error).
- Removing the `try / catch` block so error stops the execution flow which is a normal practice. This will require first checking if `proton.config.js` exists.

**Comment by dhoko** [comment]
Thx :100: 
I forgot about this feature and the missing error if the file exists :fearful: 

Now we log the error and stop the process if there is a file. If it doesn't exist we ignore the error.

**Comment by vladimiry** [comment]
Btw why not stopping the execution flow? Explicitly added `proton.config.js` becomes a part of the build process. The build process is supposed to be either successfully finished or broken but right now due to the `try/catch` bock the process might get finished with 0 status so I'd expect `proton.config.js` logic was processed but in fact, it might not. I mean I'd really prefer you don't add that `try/catch` block at all, error occurs, so let it break the build process with non-zero exit code.

**Comment by vladimiry** [comment]
Sorry I didn't notice that now there is exit 1 :+1: 

https://github.com/ProtonMail/proton-pack/blob/9f3ffa6d0e3a8e14851a7284eb6d7dc7c6072b28/cli/helpers/log.js#L29-L35
