### ISSUE TITLE
[feature request] incorporate the "version.json" file generation into the npm "npm run build ---api ..." command

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/proton-pack#61]
Right now I have to run the code like [this](https://github.com/vladimiry/ElectronMail/blob/704865abe5187bbf3e9f15ba5a83612f249f8118/scripts/prepare-webclient/protonmail.ts#L249-L282) after `npm run build ---api ...` got completed but would like the `version.json` file generation process would be incorporated into a single `npm run build ---api ...` command so I don't need to perform extra actions (especially the actions which involve direct proton's scripts execution and/or referencing the specific proton's files).

**Comment by dhoko** [comment]
:wave: 

You can run `npm run bundle` instead of `npm run build`. Proton-pack is only a wrapper on top of webpack.
We build with proton-bundler.

ex:
```sh
 npm run bundle -- --api="$API" \
   --appMode "$APP_MODE" \
   --no-lint
```

It's going to run all these tasks https://github.com/ProtonMail/proton-bundler/blob/master/lib/tasks/bundle.js (_and create the version.json_)

This command is accessible for all our apps, actually that's what we use to build the apps.

**Comment by vladimiry** [comment]
Looks like I overlooked the `bundle` cmd, going to explore it and close the issue if it handles things well.

**Comment by vladimiry** [comment]
By the way the `ProtonConfig` model comes with the `VERSION_PATH` value https://github.com/ProtonMail/proton-shared/blob/9476d55a647f8a267a135c3fcd299976b0f215ba/lib/interfaces/config.ts#L17, but the same value is also hardcoded here https://github.com/ProtonMail/proton-bundler/blob/e366ff769e770c49f5254ebc8ec0ee28cf389e40/lib/tasks/bundle.js#L106 This looks like an issue of a single source of truth absence.

**Comment by dhoko** [comment]
Indeed :thinking: 

We should move the config step inside proton-bundler instead of proton-pack. Idk why it's inside proton-pack it doesn't really make sense.

**Comment by vladimiry** [comment]
Can confirm that `npm bundle ...` run works as intended, thanks for the support.
